
COLOR_BASE_NAME_JP_MAP = {
  "b": "青",
  "g": "緑",
  "r": "赤",
  "c": "シアン",
  "m": "マゼンタ",
  "y": "黄",
  "b": "黒",
  "w": "白",
}

COLOR_NAME_JP_MAP = {
  # 無彩色・黒系
  "black": "黒",
  "dimgray": "濃い灰色",
  "gray": "灰色",
  "darkgray": "暗い灰色",
  "lightgray": "明るい灰色",
  "gainsboro": "ゲインズボロ",
  "whitesmoke": "白煙",
  "white": "白",

  # 赤系
  "red": "赤",
  "darkred": "濃赤",
  "firebrick": "耐火煉瓦色",
  "indianred": "インディアンレッド",
  "lightcoral": "薄珊瑚色",
  "salmon": "サーモンピンク",
  "darksalmon": "濃いサーモン",
  "lightsalmon": "薄いサーモン",
  "crimson": "深紅",
  "orangered": "朱赤",
  "tomato": "トマト色",

  # ピンク系
  "pink": "ピンク",
  "lightpink": "薄いピンク",
  "hotpink": "ホットピンク",
  "deeppink": "濃いピンク",
  "palevioletred": "淡い紫がかった赤",
  "mediumvioletred": "ミディアム紫がかった赤",

  # 茶色・オレンジ系
  "orange": "オレンジ",
  "darkorange": "濃いオレンジ",
  "coral": "珊瑚色",
  "chocolate": "チョコレート色",
  "saddlebrown": "サドルブラウン",
  "sienna": "シエナ",
  "brown": "茶色",
  "maroon": "栗色",
  "peru": "ペルー",
  "rosybrown": "バラ色の茶色",
  "sandybrown": "砂茶色",

  # 黄色系
  "yellow": "黄",
  "lightyellow": "薄い黄色",
  "lemonchiffon": "レモンシフォン",
  "lightgoldenrodyellow": "薄いゴールデンロッド黄",
  "papayawhip": "パパイヤホイップ",
  "moccasin": "モカシン",
  "peachpuff": "ピーチパフ",
  "palegoldenrod": "淡いゴールデンロッド",
  "khaki": "カーキ",
  "darkkhaki": "濃いカーキ",
  "gold": "金色",

  # 緑系
  "green": "緑",
  "darkgreen": "濃緑",
  "forestgreen": "森林緑",
  "seagreen": "海緑",
  "mediumseagreen": "ミディアム海緑",
  "lightseagreen": "薄い海緑",
  "palegreen": "淡緑",
  "springgreen": "春緑",
  "lawngreen": "芝生緑",
  "chartreuse": "シャルトリューズ",
  "mediumspringgreen": "ミディアム春緑",
  "greenyellow": "黄緑",
  "limegreen": "ライムグリーン",
  "yellowgreen": "黄緑色",
  "olivedrab": "オリーブ色",
  "olive": "オリーブ",
  "darkolivegreen": "濃いオリーブ緑",
  "darkseagreen": "濃い海緑",
  "mediumaquamarine": "ミディアムアクアマリン",
  "aquamarine": "アクアマリン",

  # シアン系
  "cyan": "シアン",
  "teal": "青緑",
  "darkcyan": "濃いシアン",
  "lightcyan": "薄いシアン",
  "paleturquoise": "淡いトルコ石",
  "turquoise": "トルコ石色",
  "mediumturquoise": "ミディアムトルコ石",
  "darkturquoise": "濃いトルコ石",
  "powderblue": "パウダーブルー",

  # 青系
  "blue": "青",
  "darkblue": "濃青",
  "mediumblue": "ミディアムブルー",
  "midnightblue": "真夜中の青",
  "navy": "濃紺",
  "royalblue": "ロイヤルブルー",
  "steelblue": "スチールブルー",
  "cornflowerblue": "ヤグルマギク青",
  "deepskyblue": "濃い空色",
  "dodgerblue": "ドジャーブルー",
  "lightblue": "薄い青",
  "skyblue": "空色",
  "lightskyblue": "薄い空色",
  "mediumslateblue": "ミディアムスレートブルー",
  "slateblue": "スレートブルー",
  "darkslateblue": "濃いスレートブルー",
  "lavender": "ラベンダー",
  "thistle": "シスル",
  "plum": "プラム",

  # 紫系
  "purple": "紫",
  "darkmagenta": "濃いマゼンタ",
  "magenta": "マゼンタ",
  "fuchsia": "フクシア",
  "orchid": "蘭色",
  "mediumorchid": "ミディアム蘭色",
  "darkorchid": "濃い蘭色",
  "darkviolet": "濃いスミレ色",
  "blueviolet": "青紫",
  "indigo": "藍色",
  "mediumpurple": "ミディアム紫",
  "mediumslateblue": "ミディアムスレートブルー",
  "rebeccapurple": "レベッカパープル",
  "violet": "スミレ色",

  # 白系・パステル系
  "antiquewhite": "アンティークホワイト",
  "bisque": "ビスク",
  "blanchedalmond": "ブランチドアーモンド",
  "wheat": "小麦色",
  "cornsilk": "コーンシルク",
  "lightgoldenrod": "薄いゴールデンロッド",
  "lightgoldenrodyellow": "薄いゴールデンロッド黄",
  "oldlace": "オールドレース",
  "linen": "リネン",
  "seashell": "貝殻色",
  "snow": "雪色",
  "honeydew": "ハニーデュー",
  "mintcream": "ミントクリーム",
  "azure": "空色",
  "aliceblue": "アリスブルー",
  "ghostwhite": "ゴーストホワイト",
  "floralwhite": "フローラルホワイト",
  "ivory": "象牙色",
  "lavenderblush": "ラベンダーブラッシュ",
  "mistyrose": "ミスティローズ",

  # その他
  "aquamarine": "アクアマリン",
  "turquoise": "トルコ石色",
  "silver": "銀色",
  "darkslategray": "濃いスレート灰色",
  "slategray": "スレート灰色",
  "lightslategray": "薄いスレート灰色",
  "dimgrey": "濃い灰色 (別名)",
  "grey": "灰色 (別名)",
  "lightgrey": "明るい灰色 (別名)",
  "darkgrey": "暗い灰色 (別名)",
}

COLOR_BASE_NAME_JP_MAP = {
  "b": "青",
  "g": "緑",
  "r": "赤",
  "c": "シアン",
  "m": "マゼンタ",
  "y": "黄",
  "b": "黒",
  "w": "白",
}

COLOR_NAME_JP_MAP = {
  # 無彩色・黒系
  "black": "黒",
  "dimgray": "濃い灰色",
  "gray": "灰色",
  "darkgray": "暗い灰色",
  "lightgray": "明るい灰色",
  "gainsboro": "ゲインズボロ",
  "whitesmoke": "白煙",
  "white": "白",

  # 赤系
  "red": "赤",
  "darkred": "濃赤",
  "firebrick": "耐火煉瓦色",
  "indianred": "インディアンレッド",
  "lightcoral": "薄珊瑚色",
  "salmon": "サーモンピンク",
  "darksalmon": "濃いサーモン",
  "lightsalmon": "薄いサーモン",
  "crimson": "深紅",
  "orangered": "朱赤",
  "tomato": "トマト色",

  # ピンク系
  "pink": "ピンク",
  "lightpink": "薄いピンク",
  "hotpink": "ホットピンク",
  "deeppink": "濃いピンク",
  "palevioletred": "淡い紫がかった赤",
  "mediumvioletred": "ミディアム紫がかった赤",

  # 茶色・オレンジ系
  "orange": "オレンジ",
  "darkorange": "濃いオレンジ",
  "coral": "珊瑚色",
  "chocolate": "チョコレート色",
  "saddlebrown": "サドルブラウン",
  "sienna": "シエナ",
  "brown": "茶色",
  "maroon": "栗色",
  "peru": "ペルー",
  "rosybrown": "バラ色の茶色",
  "sandybrown": "砂茶色",

  # 黄色系
  "yellow": "黄",
  "lightyellow": "薄い黄色",
  "lemonchiffon": "レモンシフォン",
  "lightgoldenrodyellow": "薄いゴールデンロッド黄",
  "papayawhip": "パパイヤホイップ",
  "moccasin": "モカシン",
  "peachpuff": "ピーチパフ",
  "palegoldenrod": "淡いゴールデンロッド",
  "khaki": "カーキ",
  "darkkhaki": "濃いカーキ",
  "gold": "金色",

  # 緑系
  "green": "緑",
  "darkgreen": "濃緑",
  "forestgreen": "森林緑",
  "seagreen": "海緑",
  "mediumseagreen": "ミディアム海緑",
  "lightseagreen": "薄い海緑",
  "palegreen": "淡緑",
  "springgreen": "春緑",
  "lawngreen": "芝生緑",
  "chartreuse": "シャルトリューズ",
  "mediumspringgreen": "ミディアム春緑",
  "greenyellow": "黄緑",
  "limegreen": "ライムグリーン",
  "yellowgreen": "黄緑色",
  "olivedrab": "オリーブ色",
  "olive": "オリーブ",
  "darkolivegreen": "濃いオリーブ緑",
  "darkseagreen": "濃い海緑",
  "mediumaquamarine": "ミディアムアクアマリン",
  "aquamarine": "アクアマリン",

  # シアン系
  "cyan": "シアン",
  "teal": "青緑",
  "darkcyan": "濃いシアン",
  "lightcyan": "薄いシアン",
  "paleturquoise": "淡いトルコ石",
  "turquoise": "トルコ石色",
  "mediumturquoise": "ミディアムトルコ石",
  "darkturquoise": "濃いトルコ石",
  "powderblue": "パウダーブルー",

  # 青系
  "blue": "青",
  "darkblue": "濃青",
  "mediumblue": "ミディアムブルー",
  "midnightblue": "真夜中の青",
  "navy": "濃紺",
  "royalblue": "ロイヤルブルー",
  "steelblue": "スチールブルー",
  "cornflowerblue": "ヤグルマギク青",
  "deepskyblue": "濃い空色",
  "dodgerblue": "ドジャーブルー",
  "lightblue": "薄い青",
  "skyblue": "空色",
  "lightskyblue": "薄い空色",
  "mediumslateblue": "ミディアムスレートブルー",
  "slateblue": "スレートブルー",
  "darkslateblue": "濃いスレートブルー",
  "lavender": "ラベンダー",
  "thistle": "シスル",
  "plum": "プラム",

  # 紫系
  "purple": "紫",
  "darkmagenta": "濃いマゼンタ",
  "magenta": "マゼンタ",
  "fuchsia": "フクシア",
  "orchid": "蘭色",
  "mediumorchid": "ミディアム蘭色",
  "darkorchid": "濃い蘭色",
  "darkviolet": "濃いスミレ色",
  "blueviolet": "青紫",
  "indigo": "藍色",
  "mediumpurple": "ミディアム紫",
  "mediumslateblue": "ミディアムスレートブルー",
  "rebeccapurple": "レベッカパープル",
  "violet": "スミレ色",

  # 白系・パステル系
  "antiquewhite": "アンティークホワイト",
  "bisque": "ビスク",
  "blanchedalmond": "ブランチドアーモンド",
  "wheat": "小麦色",
  "cornsilk": "コーンシルク",
  "lightgoldenrod": "薄いゴールデンロッド",
  "lightgoldenrodyellow": "薄いゴールデンロッド黄",
  "oldlace": "オールドレース",
  "linen": "リネン",
  "seashell": "貝殻色",
  "snow": "雪色",
  "honeydew": "ハニーデュー",
  "mintcream": "ミントクリーム",
  "azure": "空色",
  "aliceblue": "アリスブルー",
  "ghostwhite": "ゴーストホワイト",
  "floralwhite": "フローラルホワイト",
  "ivory": "象牙色",
  "lavenderblush": "ラベンダーブラッシュ",
  "mistyrose": "ミスティローズ",

  # その他
  "aquamarine": "アクアマリン",
  "turquoise": "トルコ石色",
  "silver": "銀色",
  "darkslategray": "濃いスレート灰色",
  "slategray": "スレート灰色",
  "lightslategray": "薄いスレート灰色",
  "dimgrey": "濃い灰色 (別名)",
  "grey": "灰色 (別名)",
  "lightgrey": "明るい灰色 (別名)",
  "darkgrey": "暗い灰色 (別名)",
}
